//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tojeero.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tojeero.Forms.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AlertTitleWarning {
            get {
                return ResourceManager.GetString("AlertTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tojeero.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End price.
        /// </summary>
        internal static string LabelEndPrice {
            get {
                return ResourceManager.GetString("LabelEndPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LabelMobilePhone {
            get {
                return ResourceManager.GetString("LabelMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price range.
        /// </summary>
        internal static string LabelPriceRange {
            get {
                return ResourceManager.GetString("LabelPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string LabelProductDetailsCategory {
            get {
                return ResourceManager.GetString("LabelProductDetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string LabelProductDetailsDescription {
            get {
                return ResourceManager.GetString("LabelProductDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-category:.
        /// </summary>
        internal static string LabelProductDetailsSubcategory {
            get {
                return ResourceManager.GetString("LabelProductDetailsSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        internal static string LabelProductDetailsTags {
            get {
                return ResourceManager.GetString("LabelProductDetailsTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start price.
        /// </summary>
        internal static string LabelStartPrice {
            get {
                return ResourceManager.GetString("LabelStartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        internal static string LabelSubcategory {
            get {
                return ResourceManager.GetString("LabelSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string MenuItemProfileSettings {
            get {
                return ResourceManager.GetString("MenuItemProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MessageGeneralLoading {
            get {
                return ResourceManager.GetString("MessageGeneralLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading initial data, please wait..
        /// </summary>
        internal static string MessageInitialLoading {
            get {
                return ResourceManager.GetString("MessageInitialLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for language change take effect you need to restart the app..
        /// </summary>
        internal static string MessageLanguageChangeWarning {
            get {
                return ResourceManager.GetString("MessageLanguageChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data because of unknown error. Please try again. If the issue persists please contact our support..
        /// </summary>
        internal static string MessageLoadingFailed {
            get {
                return ResourceManager.GetString("MessageLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading failed. Please make sure you have internet connection and try again..
        /// </summary>
        internal static string MessageLoadingFailedNoInternet {
            get {
                return ResourceManager.GetString("MessageLoadingFailedNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data because of timeout. Please make sure you are connected to internet and try again..
        /// </summary>
        internal static string MessageLoadingTimeOut {
            get {
                return ResourceManager.GetString("MessageLoadingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection available..
        /// </summary>
        internal static string MessageNoInternetWarning {
            get {
                return ResourceManager.GetString("MessageNoInternetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some details about you to improve your app experience..
        /// </summary>
        internal static string MessageProfileSettingsHint {
            get {
                return ResourceManager.GetString("MessageProfileSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed because of timeout. Please try again..
        /// </summary>
        internal static string MessageSubmissionTimeoutFailure {
            get {
                return ResourceManager.GetString("MessageSubmissionTimeoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed because of unknown error. Please try again. If the issue persists please contact our support..
        /// </summary>
        internal static string MessageSubmissionUnknownFailure {
            get {
                return ResourceManager.GetString("MessageSubmissionUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting data....
        /// </summary>
        internal static string MessageSubmitting {
            get {
                return ResourceManager.GetString("MessageSubmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for products.
        /// </summary>
        internal static string PlaceholderSearchProducts {
            get {
                return ResourceManager.GetString("PlaceholderSearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for stores.
        /// </summary>
        internal static string PlaceholderSearchStores {
            get {
                return ResourceManager.GetString("PlaceholderSearchStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for existing tags.
        /// </summary>
        internal static string PlaceholderSearchTags {
            get {
                return ResourceManager.GetString("PlaceholderSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite products.
        /// </summary>
        internal static string TitleFavoriteProducts {
            get {
                return ResourceManager.GetString("TitleFavoriteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string TitleFavorites {
            get {
                return ResourceManager.GetString("TitleFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite stores.
        /// </summary>
        internal static string TitleFavoriteStores {
            get {
                return ResourceManager.GetString("TitleFavoriteStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Products.
        /// </summary>
        internal static string TitleFilterProducts {
            get {
                return ResourceManager.GetString("TitleFilterProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Stores.
        /// </summary>
        internal static string TitleFilterStores {
            get {
                return ResourceManager.GetString("TitleFilterStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product details.
        /// </summary>
        internal static string TitleProductDetails {
            get {
                return ResourceManager.GetString("TitleProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string TitleProducts {
            get {
                return ResourceManager.GetString("TitleProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string TitleProfileSettings {
            get {
                return ResourceManager.GetString("TitleProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string TitleStores {
            get {
                return ResourceManager.GetString("TitleStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string TitleTags {
            get {
                return ResourceManager.GetString("TitleTags", resourceCulture);
            }
        }
    }
}
