//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tojeero.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tojeero.Forms.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AlertTitleWarning {
            get {
                return ResourceManager.GetString("AlertTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tojeero.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        internal static string ButtonAddImage {
            get {
                return ResourceManager.GetString("ButtonAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string ButtonAddProduct {
            get {
                return ResourceManager.GetString("ButtonAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags.
        /// </summary>
        internal static string ButtonAddTags {
            get {
                return ResourceManager.GetString("ButtonAddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with seller.
        /// </summary>
        internal static string ButtonChatWithSeller {
            get {
                return ResourceManager.GetString("ButtonChatWithSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string ButtonCreateProduct {
            get {
                return ResourceManager.GetString("ButtonCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a store.
        /// </summary>
        internal static string ButtonCreateStore {
            get {
                return ResourceManager.GetString("ButtonCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more messages....
        /// </summary>
        internal static string ButtonLoadMoreMessages {
            get {
                return ResourceManager.GetString("ButtonLoadMoreMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My store.
        /// </summary>
        internal static string ButtonMyStore {
            get {
                return ResourceManager.GetString("ButtonMyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read our Terms of Service.
        /// </summary>
        internal static string ButtonReadTerms {
            get {
                return ResourceManager.GetString("ButtonReadTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refetch store.
        /// </summary>
        internal static string ButtonRefetchStore {
            get {
                return ResourceManager.GetString("ButtonRefetchStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filters.
        /// </summary>
        internal static string ButtonResetFilters {
            get {
                return ResourceManager.GetString("ButtonResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string ButtonTerms {
            get {
                return ResourceManager.GetString("ButtonTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string ButtonTryAgain {
            get {
                return ResourceManager.GetString("ButtonTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add main image.
        /// </summary>
        internal static string LabelAddMainImage {
            get {
                return ResourceManager.GetString("LabelAddMainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string LabelBlocked {
            get {
                return ResourceManager.GetString("LabelBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string LabelDeclined {
            get {
                return ResourceManager.GetString("LabelDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery notes.
        /// </summary>
        internal static string LabelDeliveryNotes {
            get {
                return ResourceManager.GetString("LabelDeliveryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items in this list..
        /// </summary>
        internal static string LabelEmptyList {
            get {
                return ResourceManager.GetString("LabelEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From camera.
        /// </summary>
        internal static string LabelFromCamera {
            get {
                return ResourceManager.GetString("LabelFromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From library.
        /// </summary>
        internal static string LabelFromLibrary {
            get {
                return ResourceManager.GetString("LabelFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items in this list..
        /// </summary>
        internal static string LabelListCount {
            get {
                return ResourceManager.GetString("LabelListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        internal static string LabelMobileNumber {
            get {
                return ResourceManager.GetString("LabelMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LabelMobilePhone {
            get {
                return ResourceManager.GetString("LabelMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string LabelPending {
            get {
                return ResourceManager.GetString("LabelPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price range.
        /// </summary>
        internal static string LabelPriceRange {
            get {
                return ResourceManager.GetString("LabelPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string LabelProductDetailsCategory {
            get {
                return ResourceManager.GetString("LabelProductDetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string LabelProductDetailsDescription {
            get {
                return ResourceManager.GetString("LabelProductDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-category:.
        /// </summary>
        internal static string LabelProductDetailsSubcategory {
            get {
                return ResourceManager.GetString("LabelProductDetailsSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        internal static string LabelProductDetailsTags {
            get {
                return ResourceManager.GetString("LabelProductDetailsTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string LabelProductName {
            get {
                return ResourceManager.GetString("LabelProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string LabelStoreDetailsCategory {
            get {
                return ResourceManager.GetString("LabelStoreDetailsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string LabelStoreDetailsCity {
            get {
                return ResourceManager.GetString("LabelStoreDetailsCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string LabelStoreDetailsCountry {
            get {
                return ResourceManager.GetString("LabelStoreDetailsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Notes.
        /// </summary>
        internal static string LabelStoreDetailsDeliveryNotes {
            get {
                return ResourceManager.GetString("LabelStoreDetailsDeliveryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string LabelStoreDetailsDescription {
            get {
                return ResourceManager.GetString("LabelStoreDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Privacy.
        /// </summary>
        internal static string LabelStoreDetailsPrivacy {
            get {
                return ResourceManager.GetString("LabelStoreDetailsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name.
        /// </summary>
        internal static string LabelStoreName {
            get {
                return ResourceManager.GetString("LabelStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        internal static string LabelSubcategory {
            get {
                return ResourceManager.GetString("LabelSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string LabelTags {
            get {
                return ResourceManager.GetString("LabelTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string LabelVisible {
            get {
                return ResourceManager.GetString("LabelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string MenuItemProfileSettings {
            get {
                return ResourceManager.GetString("MenuItemProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to add your first product.
        /// </summary>
        internal static string MessageAddFirstProduct {
            get {
                return ResourceManager.GetString("MessageAddFirstProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send chat message. Please try again..
        /// </summary>
        internal static string MessageChatMessageSendingFailure {
            get {
                return ResourceManager.GetString("MessageChatMessageSendingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send chat message because of timeout. Please try again..
        /// </summary>
        internal static string MessageChatMessageSendingTimeout {
            get {
                return ResourceManager.GetString("MessageChatMessageSendingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MessageGeneralLoading {
            get {
                return ResourceManager.GetString("MessageGeneralLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading initial data, please wait..
        /// </summary>
        internal static string MessageInitialLoading {
            get {
                return ResourceManager.GetString("MessageInitialLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for language change take effect you need to restart the app..
        /// </summary>
        internal static string MessageLanguageChangeWarning {
            get {
                return ResourceManager.GetString("MessageLanguageChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data because of unknown error. Please try again. If the issue persists please contact our support..
        /// </summary>
        internal static string MessageLoadingFailed {
            get {
                return ResourceManager.GetString("MessageLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading failed. Please make sure you have internet connection and try again..
        /// </summary>
        internal static string MessageLoadingFailedNoInternet {
            get {
                return ResourceManager.GetString("MessageLoadingFailedNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading matches....
        /// </summary>
        internal static string MessageLoadingMatches {
            get {
                return ResourceManager.GetString("MessageLoadingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading store....
        /// </summary>
        internal static string MessageLoadingStore {
            get {
                return ResourceManager.GetString("MessageLoadingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data because of timeout. Please make sure you are connected to internet and try again..
        /// </summary>
        internal static string MessageLoadingTimeOut {
            get {
                return ResourceManager.GetString("MessageLoadingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} matching products..
        /// </summary>
        internal static string MessageMatchingProducts {
            get {
                return ResourceManager.GetString("MessageMatchingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} matching stores..
        /// </summary>
        internal static string MessageMatchingStores {
            get {
                return ResourceManager.GetString("MessageMatchingStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any favorite products..
        /// </summary>
        internal static string MessageNoFavoriteProducts {
            get {
                return ResourceManager.GetString("MessageNoFavoriteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any favorite stores..
        /// </summary>
        internal static string MessageNoFavoriteStores {
            get {
                return ResourceManager.GetString("MessageNoFavoriteStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection available..
        /// </summary>
        internal static string MessageNoInternetWarning {
            get {
                return ResourceManager.GetString("MessageNoInternetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no matching products..
        /// </summary>
        internal static string MessageNoMatchingProducts {
            get {
                return ResourceManager.GetString("MessageNoMatchingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no matching stores..
        /// </summary>
        internal static string MessageNoMatchingStores {
            get {
                return ResourceManager.GetString("MessageNoMatchingStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products available..
        /// </summary>
        internal static string MessageNoProducts {
            get {
                return ResourceManager.GetString("MessageNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stores available..
        /// </summary>
        internal static string MessageNoStores {
            get {
                return ResourceManager.GetString("MessageNoStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags available.
        /// </summary>
        internal static string MessageNoTags {
            get {
                return ResourceManager.GetString("MessageNoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was declined. Reason: {0}.
        /// </summary>
        internal static string MessageProductDeclined {
            get {
                return ResourceManager.GetString("MessageProductDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is pending for approval. It will be visible to the users as soon as we approve it..
        /// </summary>
        internal static string MessageProductPending {
            get {
                return ResourceManager.GetString("MessageProductPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some details about you to improve your app experience..
        /// </summary>
        internal static string MessageProfileSettingsHint {
            get {
                return ResourceManager.GetString("MessageProfileSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove image. Please try again..
        /// </summary>
        internal static string MessageRemoveImageFailure {
            get {
                return ResourceManager.GetString("MessageRemoveImageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failure.
        /// </summary>
        internal static string MessageSavingFailure {
            get {
                return ResourceManager.GetString("MessageSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving store....
        /// </summary>
        internal static string MessageSavingStore {
            get {
                return ResourceManager.GetString("MessageSavingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 matching product..
        /// </summary>
        internal static string MessageSingleMatchingProduct {
            get {
                return ResourceManager.GetString("MessageSingleMatchingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 matching store..
        /// </summary>
        internal static string MessageSingleMatchingStore {
            get {
                return ResourceManager.GetString("MessageSingleMatchingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your store has been blocked..
        /// </summary>
        internal static string MessageStoreBlocked {
            get {
                return ResourceManager.GetString("MessageStoreBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store doesn&apos;t have any products..
        /// </summary>
        internal static string MessageStoreNoProducts {
            get {
                return ResourceManager.GetString("MessageStoreNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed because of timeout. Please try again..
        /// </summary>
        internal static string MessageSubmissionTimeoutFailure {
            get {
                return ResourceManager.GetString("MessageSubmissionTimeoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed because of unknown error. Please try again. If the issue persists please contact our support..
        /// </summary>
        internal static string MessageSubmissionUnknownFailure {
            get {
                return ResourceManager.GetString("MessageSubmissionUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting data....
        /// </summary>
        internal static string MessageSubmitting {
            get {
                return ResourceManager.GetString("MessageSubmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By submitting this form you confirm that you agree to our Terms of Service.
        /// </summary>
        internal static string MessageTermsWarning {
            get {
                return ResourceManager.GetString("MessageTermsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select different name for your store. This name is reserved..
        /// </summary>
        internal static string MessageValidateInvalidStoreName {
            get {
                return ResourceManager.GetString("MessageValidateInvalidStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name should have 5 to 256 length..
        /// </summary>
        internal static string MessageValidateProductName {
            get {
                return ResourceManager.GetString("MessageValidateProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required..
        /// </summary>
        internal static string MessageValidateRequiredCategory {
            get {
                return ResourceManager.GetString("MessageValidateRequiredCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        internal static string MessageValidateRequiredCity {
            get {
                return ResourceManager.GetString("MessageValidateRequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        internal static string MessageValidateRequiredCountry {
            get {
                return ResourceManager.GetString("MessageValidateRequiredCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter non-empty name..
        /// </summary>
        internal static string MessageValidateRequiredName {
            get {
                return ResourceManager.GetString("MessageValidateRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory is required..
        /// </summary>
        internal static string MessageValidateRequiredSubcategory {
            get {
                return ResourceManager.GetString("MessageValidateRequiredSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name should have 6 to 40 length, contain only alpha-numeric characters, spaces and these special characters: -_&apos;&amp;.
        /// </summary>
        internal static string MessageValidateStoreName {
            get {
                return ResourceManager.GetString("MessageValidateStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you&apos;ve entered for your store is reserved. Please change it and try again..
        /// </summary>
        internal static string MessageValidateStoreNameReserved {
            get {
                return ResourceManager.GetString("MessageValidateStoreNameReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price should be a number greater than 0..
        /// </summary>
        internal static string MessageValidationPriceInvalid {
            get {
                return ResourceManager.GetString("MessageValidationPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your store name, country and city wisely, you won&apos;t be able to change them later..
        /// </summary>
        internal static string MessageWarningChangeStoreDetails {
            get {
                return ResourceManager.GetString("MessageWarningChangeStoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for products.
        /// </summary>
        internal static string PlaceholderSearchProducts {
            get {
                return ResourceManager.GetString("PlaceholderSearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for stores.
        /// </summary>
        internal static string PlaceholderSearchStores {
            get {
                return ResourceManager.GetString("PlaceholderSearchStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for existing tags.
        /// </summary>
        internal static string PlaceholderSearchTags {
            get {
                return ResourceManager.GetString("PlaceholderSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string TextUnknown {
            get {
                return ResourceManager.GetString("TextUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        internal static string TitleCreateProduct {
            get {
                return ResourceManager.GetString("TitleCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create store.
        /// </summary>
        internal static string TitleCreateStore {
            get {
                return ResourceManager.GetString("TitleCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        internal static string TitleEditProduct {
            get {
                return ResourceManager.GetString("TitleEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit store.
        /// </summary>
        internal static string TitleEditStore {
            get {
                return ResourceManager.GetString("TitleEditStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string TitleFailure {
            get {
                return ResourceManager.GetString("TitleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite products.
        /// </summary>
        internal static string TitleFavoriteProducts {
            get {
                return ResourceManager.GetString("TitleFavoriteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string TitleFavorites {
            get {
                return ResourceManager.GetString("TitleFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite stores.
        /// </summary>
        internal static string TitleFavoriteStores {
            get {
                return ResourceManager.GetString("TitleFavoriteStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Products.
        /// </summary>
        internal static string TitleFilterProducts {
            get {
                return ResourceManager.GetString("TitleFilterProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Stores.
        /// </summary>
        internal static string TitleFilterStores {
            get {
                return ResourceManager.GetString("TitleFilterStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick image.
        /// </summary>
        internal static string TitlePickImage {
            get {
                return ResourceManager.GetString("TitlePickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product details.
        /// </summary>
        internal static string TitleProductDetails {
            get {
                return ResourceManager.GetString("TitleProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string TitleProducts {
            get {
                return ResourceManager.GetString("TitleProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        internal static string TitleProfileSettings {
            get {
                return ResourceManager.GetString("TitleProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string TitleShop {
            get {
                return ResourceManager.GetString("TitleShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store details.
        /// </summary>
        internal static string TitleStoreDetails {
            get {
                return ResourceManager.GetString("TitleStoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string TitleStores {
            get {
                return ResourceManager.GetString("TitleStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string TitleTags {
            get {
                return ResourceManager.GetString("TitleTags", resourceCulture);
            }
        }
    }
}
